openapi: 3.0.1
info:
  title: Liftshare Acl API
  version: "1.0"
servers:
- url: https://api.appyway.com/integrations/liftshare/v1
paths:
  /commands/beginCarpoolSession:
    post:
      tags:
      - Commands
      summary: Starts an authenticated carpool parking session
      description: Starts an authenticated carpool parking session
      operationId: post-commands-begincarpoolsession
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeginCarpoolSessionCommand'
            example:
              vehicleRegistrationMark: string
              sessionStartTime: string
              parkingAssetId: string
              authenticatedTripId: string
          text/json:
            schema:
              $ref: '#/components/schemas/BeginCarpoolSessionCommand'
            example:
              vehicleRegistrationMark: string
              sessionStartTime: string
              parkingAssetId: string
              authenticatedTripId: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/BeginCarpoolSessionCommand'
            example:
              vehicleRegistrationMark: string
              sessionStartTime: string
              parkingAssetId: string
              authenticatedTripId: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeginCarpoolSessionResponseOkResponse'
              example:
                success: true
                result:
                  authenticatedTripId: string
                  sessionEndTime: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: false
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /ping:
    get:
      tags:
      - Status
      summary: Ping
      description: Returns Status (pong) of the Availability Occupancy API service
      operationId: get-ping
      responses:
        "200":
          description: Success
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the request was successful
          readOnly: true
          example: false
        message:
          type: string
          description: Human-readable message for this response
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: Collection of validation errors caused by the request
          nullable: true
      additionalProperties: false
      description: A response indicating the request was invalid
    BeginCarpoolSessionCommand:
      required:
      - authenticatedTripId
      - parkingAssetId
      - sessionStartTime
      - vehicleRegistrationMark
      type: object
      properties:
        parkingAssetId:
          minLength: 1
          type: string
          description: The id of the car park the user will be their vehicle in
        authenticatedTripId:
          minLength: 1
          type: string
          description: The Id of the authenticated liftshare trip
        vehicleRegistrationMark:
          minLength: 1
          type: string
          description: The vehicle registration mark being used for the parking session
        sessionStartTime:
          minLength: 1
          type: string
          description: |-
            The start time of the parking session
            Dates/times should be provided in ISO8601 format: YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
          format: date-time
      additionalProperties: false
    BeginCarpoolSessionResponse:
      type: object
      properties:
        authenticatedTripId:
          type: string
          description: The id of the parking session that was started
          nullable: true
        sessionEndTime:
          type: string
          description: The Date and Time that the session is scheduled to end
          format: date-time
      additionalProperties: false
      description: A response to starting a parking session
    BeginCarpoolSessionResponseOkResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the response was successful
          readOnly: true
        result:
          $ref: '#/components/schemas/BeginCarpoolSessionResponse'
      additionalProperties: false
      description: A successful response
    Error:
      type: object
      properties:
        property:
          type: string
          description: The property that caused the problem
          nullable: true
        code:
          type: string
          description: Machine-readable code representing the type of error
          nullable: true
        message:
          type: string
          description: Human-readable message for the error
          nullable: true
      additionalProperties: false
      description: Represents a validation error
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
  responses:
    TooManyRequests:
      description: Too many requests
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
security:
- apiKey: []
- oAuth2: []

