openapi: 3.0.1
info:
  title: Availability Management API
  version: "1.0"
servers:
- url: https://api.appyway.com/v1/availability-management
paths:
  /ping:
    get:
      tags:
      - Status
      summary: Returns "pong" show the API is up and running
      description: Returns "pong" show the API is up and running
      operationId: get-ping
      responses:
        "200":
          description: Success
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
  /queries/fetchDailyAvailabilitySummaryByEntityId:
    post:
      tags:
      - Availability
      summary: Fetch general daily availability summary (realtime, daily occupancy and daily predictions) by entity Id
      description: Returns the daily availability general summary (realtime, daily occupancy and daily predictions) by entity Id
      operationId: post-queries-fetchdailyavailabilitysummarybyentityid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchDailyAvailabilitySummaryByEntityIdQuery'
            example:
              id: string
              dateTime: string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchDailyAvailabilitySummaryByEntityIdQuery'
            example:
              id: string
              dateTime: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchDailyAvailabilitySummaryByEntityIdQuery'
            example:
              id: string
              dateTime: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingDailyAvailabilitySummaryOkResponse'
              example:
                success: true
                result:
                  entityId: string
                  currentAvailability:
                  - entityId: string
                    entityType: 1
                    dataSourceType: 0
                    groupId: string
                    totalSpaces: 0
                    availableSpaces: 0
                  hourlyPredictions: {}
                  occupancyHistoryForPrediction:
                  - date: string
                    entityId: string
                    occupancyBySourceType:
                    - dataSourceType: 0
                      hourlyOccupancy:
                      - 0
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /queries/fetchParkingEntitiesByAuthorityIds:
    post:
      tags:
      - Availability
      summary: /queries/fetchParkingEntitiesByAuthorityIds - POST
      operationId: post-queries-fetchparkingentitiesbyauthorityids
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchParkingEntitiesByAuthorityIdsQuery'
            example:
              ids:
              - string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchParkingEntitiesByAuthorityIdsQuery'
            example:
              ids:
              - string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchParkingEntitiesByAuthorityIdsQuery'
            example:
              ids:
              - string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingEntityIReadOnlyCollectionOkResponse'
              example:
                success: true
                result:
                - entityParentId: string
                  entityId: string
                  name: string
                  ownerId: string
                  entityType: 1
                  location: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /queries/fetchParkingOwnersEntitiesByIds:
    post:
      tags:
      - Availability
      summary: /queries/fetchParkingOwnersEntitiesByIds - POST
      operationId: post-queries-fetchparkingownersentitiesbyids
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchParkingOwnersEntitiesByIdsQuery'
            example:
              ids:
              - string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchParkingOwnersEntitiesByIdsQuery'
            example:
              ids:
              - string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchParkingOwnersEntitiesByIdsQuery'
            example:
              ids:
              - string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchParkingOwnerEntitiesByIdsQueryResultItemIReadOnlyCollectionOkResponse'
              example:
                success: true
                result:
                - id: string
                  name: string
                  parkingEntities:
                  - entityParentId: string
                    entityId: string
                    name: string
                    ownerId: string
                    entityType: 1
                    location: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        message:
          type: string
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          nullable: true
      additionalProperties: false
    DailyOccupancyForSourceType:
      type: object
      properties:
        dataSourceType:
          $ref: '#/components/schemas/DataSourceType'
        hourlyOccupancy:
          type: array
          items:
            type: number
            format: float
          nullable: true
      additionalProperties: false
    DailyOccupancyHistoryForPrediction:
      type: object
      properties:
        date:
          type: string
          format: date-time
        entityId:
          type: string
          nullable: true
        occupancyBySourceType:
          type: array
          items:
            $ref: '#/components/schemas/DailyOccupancyForSourceType'
          nullable: true
      additionalProperties: false
    DataSourceType:
      enum:
      - 0
      - 1
      - 2
      - 4
      type: integer
      format: int32
    EntityType:
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    Error:
      type: object
      properties:
        property:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    FetchDailyAvailabilitySummaryByEntityIdQuery:
      required:
      - id
      type: object
      properties:
        id:
          minLength: 1
          type: string
        dateTime:
          type: string
          format: date-time
      additionalProperties: false
    FetchParkingEntitiesByAuthorityIdsQuery:
      required:
      - ids
      type: object
      properties:
        ids:
          minLength: 1
          type: array
          items:
            type: string
      additionalProperties: false
    FetchParkingOwnerEntitiesByIdsQueryResultItem:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        parkingEntities:
          type: array
          items:
            $ref: '#/components/schemas/ParkingEntity'
          nullable: true
      additionalProperties: false
    FetchParkingOwnerEntitiesByIdsQueryResultItemIReadOnlyCollectionOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: array
          items:
            $ref: '#/components/schemas/FetchParkingOwnerEntitiesByIdsQueryResultItem'
          nullable: true
      additionalProperties: false
    FetchParkingOwnersEntitiesByIdsQuery:
      required:
      - ids
      type: object
      properties:
        ids:
          minLength: 1
          type: array
          items:
            type: string
      additionalProperties: false
    HourlyPrediction:
      type: object
      properties:
        entityId:
          type: string
          nullable: true
        occupancyRatio:
          type: number
          format: float
          nullable: true
        confidence:
          type: number
          format: float
          nullable: true
        sourceTypes:
          $ref: '#/components/schemas/DataSourceType'
      additionalProperties: false
    ParkingAvailability:
      type: object
      properties:
        entityId:
          type: string
          nullable: true
        entityType:
          $ref: '#/components/schemas/EntityType'
        dataSourceType:
          $ref: '#/components/schemas/DataSourceType'
        groupId:
          type: string
          nullable: true
        totalSpaces:
          type: integer
          format: int32
        availableSpaces:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    ParkingDailyAvailabilitySummary:
      type: object
      properties:
        entityId:
          type: string
          nullable: true
        currentAvailability:
          type: array
          items:
            $ref: '#/components/schemas/ParkingAvailability'
          nullable: true
        hourlyPredictions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/HourlyPrediction'
          nullable: true
        occupancyHistoryForPrediction:
          type: array
          items:
            $ref: '#/components/schemas/DailyOccupancyHistoryForPrediction'
          nullable: true
      additionalProperties: false
    ParkingDailyAvailabilitySummaryOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          $ref: '#/components/schemas/ParkingDailyAvailabilitySummary'
      additionalProperties: false
    ParkingEntity:
      type: object
      properties:
        entityParentId:
          type: string
          nullable: true
        entityId:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        ownerId:
          type: string
          nullable: true
        entityType:
          $ref: '#/components/schemas/EntityType'
        location:
          type: string
          nullable: true
      additionalProperties: false
    ParkingEntityIReadOnlyCollectionOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: array
          items:
            $ref: '#/components/schemas/ParkingEntity'
          nullable: true
      additionalProperties: false
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
  responses:
    TooManyRequests:
      description: Too many requests
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
security:
- apiKey: []
- oAuth2: []

