openapi: 3.0.1
info:
  title: Ylp.Enforcement.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  version: "1.0"
servers:
- url: https://api.appyway.com/parking/v1/enforcement
paths:
  /findActiveSessions:
    post:
      tags:
      - Queries
      summary: /findActiveSessions - POST
      operationId: post-findactivesessions
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/FindActiveSessionsQuery'
            example:
              locationCode: string
              vehicleRegistrationMark: string
          application/json:
            schema:
              $ref: '#/components/schemas/FindActiveSessionsQuery'
            example:
              locationCode: string
              vehicleRegistrationMark: string
          text/json:
            schema:
              $ref: '#/components/schemas/FindActiveSessionsQuery'
            example:
              locationCode: string
              vehicleRegistrationMark: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FindActiveSessionsQuery'
            example:
              locationCode: string
              vehicleRegistrationMark: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveSessionIEnumerableOkResponse'
              example:
                success: true
                result:
                - id: string
                  vehicleRegistrationMark: string
                  locationCode: string
                  startTime: string
                  expectedEndTime: string
                  paymentTime: string
                  amountPaid: 0
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /notifyEnforcementOfParkingSession:
    post:
      tags:
      - Commands
      summary: /notifyEnforcementOfParkingSession - POST
      operationId: post-notifyenforcementofparkingsession
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/NotifyEnforcementOfParkingSessionCommand'
            example:
              id: string
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyEnforcementOfParkingSessionCommand'
            example:
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/NotifyEnforcementOfParkingSessionCommand'
            example:
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/NotifyEnforcementOfParkingSessionCommand'
            example:
              id: string
      responses:
        "202":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringOkResponse'
              example:
                success: true
                result: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: true
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /ping:
    get:
      tags:
      - Status
      summary: /ping - GET
      operationId: get-ping
      responses:
        "200":
          description: Success
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
components:
  schemas:
    ActiveSession:
      type: object
      properties:
        id:
          type: string
          nullable: true
        vehicleRegistrationMark:
          type: string
          nullable: true
        locationCode:
          type: string
          nullable: true
        startTime:
          type: string
          format: date-time
        expectedEndTime:
          type: string
          format: date-time
          nullable: true
        paymentTime:
          type: string
          format: date-time
          nullable: true
        amountPaid:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    ActiveSessionIEnumerableOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: array
          items:
            $ref: '#/components/schemas/ActiveSession'
          nullable: true
      additionalProperties: false
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        message:
          type: string
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          nullable: true
      additionalProperties: false
    Error:
      type: object
      properties:
        property:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    FindActiveSessionsQuery:
      type: object
      properties:
        locationCode:
          type: string
          nullable: true
        vehicleRegistrationMark:
          type: string
          nullable: true
      additionalProperties: false
    NotifyEnforcementOfParkingSessionCommand:
      type: object
      properties:
        id:
          type: string
          nullable: true
      additionalProperties: false
    StringOkResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        result:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
  responses:
    TooManyRequests:
      description: Too many requests
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
security:
- apiKey: []
- oAuth2: []

