openapi: 3.0.1
info:
  title: Availability Occupancy API
  version: "1.0"
servers:
- url: https://api.appyway.com/v1/availability-occupancy
paths:
  /commands/recordOccupancy:
    post:
      tags:
      - Availability
      summary: /commands/recordOccupancy - POST
      operationId: post-commands-recordoccupancy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordOccupancyCommand'
            example:
              receivedOn: string
              source: string
              entityId: string
              entityType: 1
              dataSourceType: 0
              timestampUtc: string
              vacantSpaces: 0
              occupiedSpaces: 0
              groupId: string
          text/json:
            schema:
              $ref: '#/components/schemas/RecordOccupancyCommand'
            example:
              receivedOn: string
              source: string
              entityId: string
              entityType: 1
              dataSourceType: 0
              timestampUtc: string
              vacantSpaces: 0
              occupiedSpaces: 0
              groupId: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/RecordOccupancyCommand'
            example:
              receivedOn: string
              source: string
              entityId: string
              entityType: 1
              dataSourceType: 0
              timestampUtc: string
              vacantSpaces: 0
              occupiedSpaces: 0
              groupId: string
      responses:
        "200":
          description: Success
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /ping:
    get:
      tags:
      - Status
      summary: Ping
      description: Returns Status (pong) of the Availability Occupancy API service
      operationId: get-ping
      responses:
        "200":
          description: Success
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
  /queries/fetchCurrentDayHourlyOccupancyHistoryByEntityId:
    post:
      tags:
      - Availability
      summary: Fetch current day hourly occupancy history by entity id
      description: Returns the current day hourly occupancy history as an occupancy ratio (between 0 and 1) for the given entity id.
      operationId: post-queries-fetchcurrentdayhourlyoccupancyhistorybyentityid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchCurrentDayHourlyOccupancyHistoryByEntityIdQuery'
            example:
              id: string
          text/json:
            schema:
              $ref: '#/components/schemas/FetchCurrentDayHourlyOccupancyHistoryByEntityIdQuery'
            example:
              id: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/FetchCurrentDayHourlyOccupancyHistoryByEntityIdQuery'
            example:
              id: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Int32DoubleIDictionaryOkResponse'
              example:
                success: true
                result: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                success: false
                message: string
                errors:
                - property: string
                  code: string
                  message: string
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "429":
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    EntityType:
      enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    DataSourceType:
      enum:
      - 0
      - 1
      - 2
      - 4
      type: integer
      format: int32
    RecordOccupancyCommand:
      type: object
      properties:
        receivedOn:
          type: string
          format: date-time
          nullable: true
        source:
          type: string
          nullable: true
        entityId:
          type: string
          nullable: true
        entityType:
          $ref: '#/components/schemas/EntityType'
        dataSourceType:
          $ref: '#/components/schemas/DataSourceType'
        timestampUtc:
          type: string
          format: date-time
        vacantSpaces:
          type: integer
          format: int32
          nullable: true
        occupiedSpaces:
          type: integer
          format: int32
          nullable: true
        groupId:
          type: string
          nullable: true
      additionalProperties: false
    FetchCurrentDayHourlyOccupancyHistoryByEntityIdQuery:
      required:
      - id
      type: object
      properties:
        id:
          minLength: 1
          type: string
          nullable: true
      additionalProperties: false
    Int32DoubleIDictionaryOkResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the response was successful
          readOnly: true
        result:
          type: object
          additionalProperties:
            type: number
            format: double
          description: Payload of the response
          nullable: true
      additionalProperties: false
      description: A successful response
    Error:
      type: object
      properties:
        property:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    BadRequestResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the request was successful
          readOnly: true
          example: false
        message:
          type: string
          description: Human-readable message for this response
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: Collection of validation errors caused by the request
          nullable: true
      additionalProperties: false
      description: A response indicating the request was invalid
  securitySchemes:
    apiKey:
      name: API-KEY
      in: header
      type: apiKey
    oAuth2:
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://auth.appyway.com/authorize
          tokenUrl: https://auth.appyway.com/oauth/token
      type: oauth2
  responses:
    TooManyRequests:
      description: Too many requests
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
security:
- apiKey: []
- oAuth2: []

